import jsPDF from "jspdf";

interface Args {
  language: string;
  summaryBullets: string[];
  explanation: string;
  findings: { term: string; plain: string }[];
  worryLevel: string;
  agePercent: number;
  envPercent: number;
  ageBullets: string[];
  envBullets: string[];
  fullReport: string;
  comparison?: string;
  nextSteps: string[];
}

export const generateReportPDF = (a: Args) => {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = 50;
  let y = M;
  const reportId = `DX-${Math.floor(100000 + Math.random() * 900000)}`;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const ensureSpace = (h: number) => {
    if (y + h > pageH - M) {
      doc.addPage();
      y = M;
    }
  };

  const writeText = (text: string, opts: { size?: number; bold?: boolean; color?: [number, number, number]; gap?: number; lineH?: number } = {}) => {
    const { size = 10, bold = false, color = [30, 41, 59], gap = 4, lineH } = opts;
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, pageW - M * 2);
    const lh = lineH || size * 1.3;
    lines.forEach((line: string) => {
      ensureSpace(lh);
      doc.text(line, M, y);
      y += lh;
    });
    y += gap;
  };

  const divider = () => {
    ensureSpace(20);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(M, y, pageW - M, y);
    y += 14;
  };

  const heading = (text: string) => {
    ensureSpace(28);
    doc.setFillColor(37, 99, 235);
    doc.rect(M, y - 4, 4, 16, "F");
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(text, M + 12, y + 8);
    y += 22;
  };

  // ==== HEADER ====
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 70, "F");
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("DECODEX", M, 38);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AI Medical Report Analysis", M, 56);
  y = 100;

  writeText(`Generated on: ${today}`, { size: 9, color: [100, 116, 139] });
  writeText(`Patient Report ID: ${reportId}`, { size: 9, color: [100, 116, 139] });
  writeText(`Language: ${a.language}`, { size: 9, color: [100, 116, 139], gap: 8 });
  divider();

  // ==== EXECUTIVE SUMMARY ====
  heading("EXECUTIVE SUMMARY");
  a.summaryBullets.forEach((b) => writeText(`•  ${b}`, { size: 10, gap: 2 }));
  y += 6;
  divider();

  // ==== AI EXPLANATION ====
  heading("AI EXPLANATION");
  writeText(a.explanation, { size: 10, gap: 8 });
  divider();

  // ==== FINDINGS ====
  heading("FINDINGS BREAKDOWN");
  a.findings.forEach((f, i) => {
    writeText(`Finding ${i + 1}: ${f.term}`, { size: 10, bold: true, gap: 2 });
    writeText(`→ ${f.plain}`, { size: 10, color: [71, 85, 105], gap: 8 });
  });
  divider();

  // ==== WORRY LEVEL ====
  heading("WORRY LEVEL");
  writeText(a.worryLevel.toUpperCase(), { size: 14, bold: true, color: [217, 119, 6], gap: 10 });
  divider();

  // ==== CAUSE INSIGHTS ====
  heading("CAUSE INSIGHTS");
  writeText(`Age-Related Factors (${a.agePercent}%):`, { size: 11, bold: true, color: [124, 58, 237], gap: 4 });
  a.ageBullets.forEach((b) => writeText(`•  ${b}`, { size: 10, gap: 2 }));
  y += 6;
  writeText(`Environmental Factors (${a.envPercent}%):`, { size: 11, bold: true, color: [16, 185, 129], gap: 4 });
  a.envBullets.forEach((b) => writeText(`•  ${b}`, { size: 10, gap: 2 }));
  y += 6;
  divider();

  // ==== FULL REPORT ====
  heading("FULL DETAILED REPORT");
  writeText(a.fullReport, { size: 9.5, gap: 8, lineH: 13 });
  divider();

  // ==== COMPARISON ====
  if (a.comparison) {
    heading("COMPARISON WITH PREVIOUS REPORT");
    writeText(a.comparison, { size: 10, gap: 8 });
    divider();
  }

  // ==== NEXT STEPS ====
  heading("SUGGESTED NEXT STEPS");
  a.nextSteps.forEach((s, i) => writeText(`${i + 1}.  ${s}`, { size: 10, gap: 4 }));
  y += 8;
  divider();

  // ==== DISCLAIMER ====
  ensureSpace(60);
  doc.setFillColor(248, 250, 252);
  doc.rect(M, y, pageW - M * 2, 56, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(71, 85, 105);
  const dis = doc.splitTextToSize(
    "DISCLAIMER: This report is generated by Decodex AI for informational purposes only. It does not constitute medical advice. Please consult a qualified doctor.",
    pageW - M * 2 - 16
  );
  let dy = y + 16;
  dis.forEach((l: string) => {
    doc.text(l, M + 8, dy);
    dy += 11;
  });
  y += 64;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text("Support: support@decodex.com  |  +91-9999999999", M, y);

  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Decodex • Report ${reportId}`, M, pageH - 20);
    doc.text(`Page ${i} / ${pageCount}`, pageW - M, pageH - 20, { align: "right" });
  }

  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`Decodex_Report_${dateStr}.pdf`);
  return reportId;
};
